######################################################################
##
## Filename: CPU_tb.udo
## Created on: Sat Nov 29 10:22:09 AM US Mountain Standard Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
